#!/usr/bin/env node
'use strict';

/**
 * list-vessels.js
 *
 * Runs the parser against all historical PDFs and outputs:
 *   1. A deduplicated, sorted list of all vessel names seen (stdout)
 *   2. A ready-to-run SQL INSERT for vessel_aliases (stdout, as a comment block)
 *
 * Usage:
 *   node scripts/list-vessels.js
 *   node scripts/list-vessels.js --csv          # output CSV only
 *   node scripts/list-vessels.js --sql          # output SQL INSERT only
 *   node scripts/list-vessels.js --count        # summary stats only
 *
 * The SQL output is a starting point — aliases map raw name -> canonical name.
 * Edit canonical_name values before running if you want to merge variants.
 */

const path = require('path');
const fs   = require('fs');
const { parsePdf } = require('../lib/parse-pdf');

const PDF_DIR = path.join(__dirname, '..');

const args   = process.argv.slice(2);
const csvOnly   = args.includes('--csv');
const sqlOnly   = args.includes('--sql');
const countOnly = args.includes('--count');

// Find all historical PDFs
const pdfFiles = fs.readdirSync(PDF_DIR)
  .filter(f => f.startsWith('Report_LineupSintetico3_') && f.endsWith('.pdf'))
  .map(f => path.join(PDF_DIR, f))
  .sort();

if (pdfFiles.length === 0) {
  console.error('Nenhum PDF encontrado em', PDF_DIR);
  process.exit(1);
}

console.error(`Processando ${pdfFiles.length} PDFs...`);

// Collect all vessel names: canonical -> Set of raw variants
const vesselMap = new Map(); // canonical -> Set<raw>
const reportDates = [];
let totalVessels = 0;
const warnings = [];

for (const pdfPath of pdfFiles) {
  const filename = path.basename(pdfPath);
  try {
    const result = parsePdf(pdfPath);
    reportDates.push(result.reportDate || filename);
    totalVessels += result.vessels.length;

    for (const v of result.vessels) {
      const canonical = v.vessel_name_canonical;
      const raw       = v.vessel_name_raw;
      if (!vesselMap.has(canonical)) {
        vesselMap.set(canonical, new Set());
      }
      vesselMap.get(canonical).add(raw);
    }

    if (result.warnings.length > 0) {
      warnings.push(`${filename}: ${result.warnings.length} aviso(s)`);
    }
    console.error(`  OK  ${filename} — ${result.vessels.length} navios`);
  } catch (e) {
    console.error(`  ERR ${filename} — ${e.message}`);
  }
}

const uniqueCount = vesselMap.size;

if (countOnly) {
  console.log(`PDFs processados:   ${pdfFiles.length}`);
  console.log(`Total vessel rows:  ${totalVessels}`);
  console.log(`Navios unicos:      ${uniqueCount}`);
  if (warnings.length > 0) {
    console.log(`\nAvisos:`);
    warnings.forEach(w => console.log(`  ${w}`));
  }
  process.exit(0);
}

// Sort canonical names alphabetically
const sorted = [...vesselMap.entries()].sort(([a], [b]) => a.localeCompare(b));

if (!sqlOnly) {
  // CSV output: canonical_name, raw_variants
  if (!countOnly) {
    console.log('canonical_name,raw_variants');
    for (const [canonical, raws] of sorted) {
      const rawList = [...raws].join(' | ');
      // Escape CSV
      const escapedCanonical = canonical.includes(',') ? `"${canonical}"` : canonical;
      const escapedRaw = rawList.includes(',') ? `"${rawList}"` : rawList;
      console.log(`${escapedCanonical},${escapedRaw}`);
    }
  }
}

if (sqlOnly || !csvOnly) {
  // SQL INSERT for vessel_aliases
  // One row per canonical name, using the canonical as both alias and canonical_name
  // (baseline: alias = canonical = UPPER(TRIM(raw)))
  const lines = [];
  lines.push('-- vessel_aliases seed — generated by scripts/list-vessels.js');
  lines.push(`-- ${uniqueCount} unique vessels from ${pdfFiles.length} PDFs (${totalVessels} total rows)`);
  lines.push('-- Edit canonical_name to merge variants before running.');
  lines.push('-- Example: change canonical_name of "BUBBA BOOSH" alias to "BUBBA BOOSH" (or whatever the correct name is)');
  lines.push('');
  lines.push('INSERT INTO vessel_aliases (alias, canonical_name) VALUES');

  const rows = sorted.map(([canonical]) => {
    const escaped = canonical.replace(/'/g, "''");
    return `  ('${escaped}', '${escaped}')`;
  });
  lines.push(rows.join(',\n') + ';');

  if (sqlOnly) {
    console.log(lines.join('\n'));
  } else {
    console.log('\n-- ---------------------------------------------------------------');
    console.log(lines.join('\n'));
  }
}
